//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHXE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        [Display(Name = "Mã chi tiết")]
        public int ID { get; set; }

        [Display(Name = "Đơn đặt hàng")]

        public Nullable<int> DonHang_ID { get; set; }

        [Display(Name = "Sách")]

        public Nullable<int> Xe_ID { get; set; }

        [Display(Name = "Số lượng")]

        public Nullable<short> SoLuong { get; set; }
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Display(Name = "Đơn giá")]

        public Nullable<long> DonGia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
