//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHXE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        [Display(Name = "Mã đơn hàng")]
        public int ID { get; set; }


        [Display(Name = "Nhân viên")]
       
        public Nullable<int> NhanVien_ID { get; set; }

        [Display(Name = "Khách hàng")]
        
        public Nullable<int> KhachHang_ID { get; set; }

        [Display(Name = "Số Điện Thoại Giao Hàng")]
        [Required(ErrorMessage = "Số Điện Thoại Giao Hàng không được bỏ trống!")]
        [RegularExpression(@"((09|03|07|08|05)\d{8})$", ErrorMessage = ("Số điện thoại Giao Hàng không đúng!"))]
        public string SDTGiaoHang { get; set; }

        [Display(Name = "Ngày đặt hàng")]
        
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> NgayDatHang { get; set; }

        [Display(Name = "Địa chỉ giao hàng")]
        [Required(ErrorMessage = "Địa chỉ giao hàng không được bỏ trống!")]
        public string DiaChiGiaoHang { get; set; }

        [Display(Name = "Tình trạng đơn hàng")]
        
        public Nullable<short> TinhTrang { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
    }
}
