//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHXE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.DonHang = new HashSet<DonHang>();
        }

        [Display(Name = "Mã NV")]
        public int ID { get; set; }

        [Display(Name = "Họ & Tên Nhân Viên")]
        [Required(ErrorMessage = "Họ và tên không được bỏ trống!")]
        public string HovaTen { get; set; }
        [Display(Name = "Số Điện Thoại")]
        [Required(ErrorMessage = "Số Điện Thoại không được bỏ trống!")]
        [RegularExpression(@"((09|03|07|08|05)\d{8})$", ErrorMessage = ("Số điện thoại không đúng!"))]
        public string SDT { get; set; }

        [Display(Name = "Địa Chỉ")]
        [Required(ErrorMessage = "Địa Chỉ không được bỏ trống!")]
        public string DiaChi { get; set; }

        [Display(Name = "Tên Đăng Nhập")]
        [Required(ErrorMessage = "Tên Đăng Nhập không được bỏ trống!")]
        public string TenDangNhap { get; set; }

        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage = "Mật Khẩu không được bỏ trống!")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }

        [Display(Name = "Xác nhận mật khẩu")]
        [Required(ErrorMessage = "Xác nhận mật khẩu không được bỏ trống!")]
        [Compare("MatKhau", ErrorMessage = "Xác nhận mật khẩu không chính xác!")]
        [DataType(DataType.Password)]

        public string XacNhanMatKhau { get; set; }
        [Display(Name = "Quyền")]
        [Required(ErrorMessage = "Chưa chọn quyền hạn!")]
        public Nullable<bool> Quyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
    }

   
}
