//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHXE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        [Display(Name = "Mã xe")]
        public int ID { get; set; }
        [Display(Name = "Thương hiệu")]
        [Required(ErrorMessage = "Chưa chọn thương hiệu!")]
        public Nullable<int> ThuongHieu_ID { get; set; }

        [Display(Name = "Nhà nơi SX")]
        [Required(ErrorMessage = "Chưa chọn nơi sx!")]
        public Nullable<int> NoiSanXuat_ID { get; set; }

        [Display(Name = "Loại Xe")]
        [Required(ErrorMessage = "Chưa chọn loại!")]
        public Nullable<int> LoaiXe_ID { get; set; }

        [Display(Name = "Tên xe")]
        [Required(ErrorMessage = "Tên xe không được bỏ trống!")]
        public string TenXe { get; set; }

        [Display(Name = "Màu xe")]
        [Required(ErrorMessage = "Màu xe không được bỏ trống!")]
        public string MauXe { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Đơn giá")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Đơn giá bản không được bỏ trống!")]
        public Nullable<long> DonGia { get; set; }


        [Display(Name = "Chính sách bảo hành")]
        [Required(ErrorMessage = "Chính sách bảo hành không được bỏ trống!")]
        public Nullable<int> ThoiHanBaoHanh { get; set; }

        [Display(Name = "Hình ảnh bìa")]
        public string HinhAnhBia { get; set; }
        [Display(Name = "Hình ảnh bìa")]
        public HttpPostedFileBase DuLieuHinhAnhBia { get; set; }

        [Display(Name = "Mô tả xe")]
        [DataType(DataType.MultilineText)]
        public string MoTa { get; set; }

        public virtual LoaiXe LoaiXe { get; set; }
        public virtual NoiSanXuat NoiSanXuat { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
    }
}
