//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class BangPhanCong
    {
        public int ID { get; set; }

        [Display(Name = "Hướng dẫn")]
        [Required(ErrorMessage = "Nhân viên hướng dẫn chưa được chọn")]
        public Nullable<int> NhanVien_ID { get; set; }

        [Display(Name = "Tour")]
        [Required(ErrorMessage = "Vui lòng chọn Tour!!!")]
        public Nullable<int> Tour_ID { get; set; }

        [Display(Name = "Ngày bắt đầu")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayBD { get; set; }

        [Display(Name = "Ngày kết thúc")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayKT { get; set; }

        public IEnumerable<SelectListItem> NhanVien_IDs { get; set; }

        public virtual NhanVien NhanVien { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
