//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int ID { get; set; }
        public Nullable<int> BaiViet_ID { get; set; }
        public Nullable<int> KhachHang_ID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<byte> KiemDuyet { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
