//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingTravelEntities : DbContext
    {
        public BookingTravelEntities()
            : base("name=BookingTravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhuongTien> PhuongTien { get; set; }
        public virtual DbSet<BaiViet> BaiViet { get; set; }
        public virtual DbSet<BinhLuan> BinhLuan { get; set; }
        public virtual DbSet<ChiTietDiaDiemThamQuan> ChiTietDiaDiemThamQuan { get; set; }
        public virtual DbSet<ChiTietPhuongTien> ChiTietPhuongTien { get; set; }
        public virtual DbSet<DatTour> DatTour { get; set; }
        public virtual DbSet<DatTour_ChiTiet> DatTour_ChiTiet { get; set; }
        public virtual DbSet<DiaDiemThamQuan> DiaDiemThamQuan { get; set; }
        public virtual DbSet<HinhAnh> HinhAnh { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhachSan> KhachSan { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ChiTietDichVu> ChiTietDichVu { get; set; }
        public virtual DbSet<BangPhanCong> BangPhanCong { get; set; }
    }
}
