//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatTour()
        {
            this.DatTour_ChiTiet = new HashSet<DatTour_ChiTiet>();
        }

        [Display(Name = "Mã đặt tour")]
        public int ID { get; set; }


        [Display(Name = "Nhân viên")]
        public Nullable<int> NhanVien_ID { get; set; }

        [Display(Name = "Khách hàng")]
        public Nullable<int> KhachHang_ID { get; set; }

        [Display(Name = "Điện thoại")]
        [Required(ErrorMessage = "Điện thoại không được bỏ trống!")]
        public string DienThoaiDatTour { get; set; }

        [Display(Name = "Họ và tên")]
        [Required(ErrorMessage = "Họ và tên không được bỏ trống!")]
        public string HoVaTen { get; set; }

        [Display(Name = "Ngày đặt")]
        public Nullable<System.DateTime> NgayDatHang { get; set; }

        [Display(Name = "Tình trạng")]
        public Nullable<short> TinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTour_ChiTiet> DatTour_ChiTiet { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
