//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatTour()
        {
            this.DatTour_ChiTiet = new HashSet<DatTour_ChiTiet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NhanVien_ID { get; set; }
        public Nullable<int> KhachHang_ID { get; set; }
        public string DienThoaiDatTour { get; set; }
        public string HoVaTen { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<short> TinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTour_ChiTiet> DatTour_ChiTiet { get; set; }
    }
}
