//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatTour_ChiTiet
    {
        public int ID { get; set; }
        public Nullable<int> DatTour_ID { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual DatTour DatTour { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
