//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class HinhAnh
    {
        [Display(Name = "Mã hình ảnh")]
        public int ID { get; set; }

        [Display(Name = "Tour")]
        [Required(ErrorMessage = "Chưa chọn tuor!")]
        public Nullable<int> Tour_ID { get; set; }

        [Display(Name = "Hình ảnh")]
        public string HinhAnh1 { get; set; }

        [Display(Name = "Hình ảnh bìa")]
        public HttpPostedFileBase DuLieuHinhAnh{ get; set; }

        public virtual Tour Tour { get; set; }
    }
}
